
import { Container, Col, Row } from "react-bootstrap"
export default function About(props) {

    return (
        <Container fluid>
            <Col xs={9} className="about-page">
                <h2>About</h2>

<p>The Online Federal Crime Resource Center is a search engine that allows the review of the FBI's and national law enforcement's annually compiled crime and arrest records and statistics.  This Website is made possible by the Uniform Crime Reporting (UCR) Program.</p>

<p>The FBI has been collecting data on crimes and arrests since 1930, originally as part of the Summary Reporting System (SRS) and now the more robust and detailed National Incident-Based Reporting System (NIBRS).</p>

<p>According to the FBI, "The UCR Program includes data from more than 18,000 city, university and college, county, state, tribal, and federal law enforcement agencies. Agencies participate voluntarily and submit their crime data either through a state UCR program or directly to the FBI's UCR Program."</p>

<p>The statics and charts generated by this Website is made available exclusively through API calls to the FBI-CDE Crime-Data-API front end, which can be accessed via it's GitHub repository location: <a href="https://github.com/fbi-cde/crime-data-api" target="_blank">https://github.com/fbi-cde/crime-data-api.</a></p>

<footer>
<p>Sources:</p>
<p>"SRS to NIBRS", Federal Bureau of Investigations Website, https://www.fbi.gov/services/cjis/cjis-link/srs-to-nibrs-the-path-to-better-ucr-data<br />
</p>
<p>"UCR Publications", Federal Bureau of Investigations Website, https://www.fbi.gov/services/cjis/ucr/publications</p>
</footer>

            </Col>
        </Container>
    )

}

